[package]
name = "test_crate"
version = "0.1.0"
authors = ["SveOls <sverre.d.olsen@live.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.21.0"
rand = "0.7.3"
minifb = "0.15.3"
bmp = "0.5.0"